development:
  adapter: postgresql
  encoding: unicode
  database: gloveslap-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gloveslap-test
  pool: 5
  port: 5432
  host: localhost
